# Generated by Django 5.0.6 on 2024-06-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
