# Generated by Django 5.0.6 on 2024-06-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_pokemon_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='id',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
